import './globals.css'
import { Inter, Source_Code_Pro } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const SC = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-SC",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${SC.className} `}>{children}</body>
    </html>
  )
}
